// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: protoc/storage.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StorageService_StoreV1_FullMethodName    = "/dist_file_storage.StorageService/StoreV1"
	StorageService_DownloadV1_FullMethodName = "/dist_file_storage.StorageService/DownloadV1"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServiceClient interface {
	StoreV1(ctx context.Context, opts ...grpc.CallOption) (StorageService_StoreV1Client, error)
	DownloadV1(ctx context.Context, in *DownloadV1Request, opts ...grpc.CallOption) (StorageService_DownloadV1Client, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) StoreV1(ctx context.Context, opts ...grpc.CallOption) (StorageService_StoreV1Client, error) {
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[0], StorageService_StoreV1_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &storageServiceStoreV1Client{stream}
	return x, nil
}

type StorageService_StoreV1Client interface {
	Send(*StoreV1Request) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type storageServiceStoreV1Client struct {
	grpc.ClientStream
}

func (x *storageServiceStoreV1Client) Send(m *StoreV1Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storageServiceStoreV1Client) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageServiceClient) DownloadV1(ctx context.Context, in *DownloadV1Request, opts ...grpc.CallOption) (StorageService_DownloadV1Client, error) {
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[1], StorageService_DownloadV1_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &storageServiceDownloadV1Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StorageService_DownloadV1Client interface {
	Recv() (*DownloadV1Response, error)
	grpc.ClientStream
}

type storageServiceDownloadV1Client struct {
	grpc.ClientStream
}

func (x *storageServiceDownloadV1Client) Recv() (*DownloadV1Response, error) {
	m := new(DownloadV1Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations should embed UnimplementedStorageServiceServer
// for forward compatibility
type StorageServiceServer interface {
	StoreV1(StorageService_StoreV1Server) error
	DownloadV1(*DownloadV1Request, StorageService_DownloadV1Server) error
}

// UnimplementedStorageServiceServer should be embedded to have forward compatible implementations.
type UnimplementedStorageServiceServer struct {
}

func (UnimplementedStorageServiceServer) StoreV1(StorageService_StoreV1Server) error {
	return status.Errorf(codes.Unimplemented, "method StoreV1 not implemented")
}
func (UnimplementedStorageServiceServer) DownloadV1(*DownloadV1Request, StorageService_DownloadV1Server) error {
	return status.Errorf(codes.Unimplemented, "method DownloadV1 not implemented")
}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_StoreV1_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).StoreV1(&storageServiceStoreV1Server{stream})
}

type StorageService_StoreV1Server interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*StoreV1Request, error)
	grpc.ServerStream
}

type storageServiceStoreV1Server struct {
	grpc.ServerStream
}

func (x *storageServiceStoreV1Server) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storageServiceStoreV1Server) Recv() (*StoreV1Request, error) {
	m := new(StoreV1Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StorageService_DownloadV1_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadV1Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).DownloadV1(m, &storageServiceDownloadV1Server{stream})
}

type StorageService_DownloadV1Server interface {
	Send(*DownloadV1Response) error
	grpc.ServerStream
}

type storageServiceDownloadV1Server struct {
	grpc.ServerStream
}

func (x *storageServiceDownloadV1Server) Send(m *DownloadV1Response) error {
	return x.ServerStream.SendMsg(m)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dist_file_storage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StoreV1",
			Handler:       _StorageService_StoreV1_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadV1",
			Handler:       _StorageService_DownloadV1_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protoc/storage.proto",
}
