// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: protoc/storage.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreRequestMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *StoreRequestMetadata) Reset() {
	*x = StoreRequestMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreRequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequestMetadata) ProtoMessage() {}

func (x *StoreRequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequestMetadata.ProtoReflect.Descriptor instead.
func (*StoreRequestMetadata) Descriptor() ([]byte, []int) {
	return file_protoc_storage_proto_rawDescGZIP(), []int{0}
}

func (x *StoreRequestMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StoreV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*StoreV1Request_Meta
	//	*StoreV1Request_Content
	Data isStoreV1Request_Data `protobuf_oneof:"data"`
}

func (x *StoreV1Request) Reset() {
	*x = StoreV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreV1Request) ProtoMessage() {}

func (x *StoreV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreV1Request.ProtoReflect.Descriptor instead.
func (*StoreV1Request) Descriptor() ([]byte, []int) {
	return file_protoc_storage_proto_rawDescGZIP(), []int{1}
}

func (m *StoreV1Request) GetData() isStoreV1Request_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *StoreV1Request) GetMeta() *StoreRequestMetadata {
	if x, ok := x.GetData().(*StoreV1Request_Meta); ok {
		return x.Meta
	}
	return nil
}

func (x *StoreV1Request) GetContent() []byte {
	if x, ok := x.GetData().(*StoreV1Request_Content); ok {
		return x.Content
	}
	return nil
}

type isStoreV1Request_Data interface {
	isStoreV1Request_Data()
}

type StoreV1Request_Meta struct {
	Meta *StoreRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type StoreV1Request_Content struct {
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*StoreV1Request_Meta) isStoreV1Request_Data() {}

func (*StoreV1Request_Content) isStoreV1Request_Data() {}

type DownloadV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *DownloadV1Request) Reset() {
	*x = DownloadV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadV1Request) ProtoMessage() {}

func (x *DownloadV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadV1Request.ProtoReflect.Descriptor instead.
func (*DownloadV1Request) Descriptor() ([]byte, []int) {
	return file_protoc_storage_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadV1Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DownloadV1Response) Reset() {
	*x = DownloadV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadV1Response) ProtoMessage() {}

func (x *DownloadV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadV1Response.ProtoReflect.Descriptor instead.
func (*DownloadV1Response) Descriptor() ([]byte, []int) {
	return file_protoc_storage_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadV1Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_protoc_storage_proto protoreflect.FileDescriptor

var file_protoc_storage_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0x73, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x11, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x22, 0x28, 0x0a, 0x12, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x31, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xb5, 0x01, 0x0a, 0x0e,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46,
	0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x31, 0x12, 0x21, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x12, 0x5b, 0x0a, 0x0a, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x56, 0x31, 0x12, 0x24, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_storage_proto_rawDescOnce sync.Once
	file_protoc_storage_proto_rawDescData = file_protoc_storage_proto_rawDesc
)

func file_protoc_storage_proto_rawDescGZIP() []byte {
	file_protoc_storage_proto_rawDescOnce.Do(func() {
		file_protoc_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_storage_proto_rawDescData)
	})
	return file_protoc_storage_proto_rawDescData
}

var file_protoc_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protoc_storage_proto_goTypes = []interface{}{
	(*StoreRequestMetadata)(nil), // 0: dist_file_storage.StoreRequestMetadata
	(*StoreV1Request)(nil),       // 1: dist_file_storage.StoreV1Request
	(*DownloadV1Request)(nil),    // 2: dist_file_storage.DownloadV1Request
	(*DownloadV1Response)(nil),   // 3: dist_file_storage.DownloadV1Response
	(*emptypb.Empty)(nil),        // 4: google.protobuf.Empty
}
var file_protoc_storage_proto_depIdxs = []int32{
	0, // 0: dist_file_storage.StoreV1Request.meta:type_name -> dist_file_storage.StoreRequestMetadata
	1, // 1: dist_file_storage.StorageService.StoreV1:input_type -> dist_file_storage.StoreV1Request
	2, // 2: dist_file_storage.StorageService.DownloadV1:input_type -> dist_file_storage.DownloadV1Request
	4, // 3: dist_file_storage.StorageService.StoreV1:output_type -> google.protobuf.Empty
	3, // 4: dist_file_storage.StorageService.DownloadV1:output_type -> dist_file_storage.DownloadV1Response
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoc_storage_proto_init() }
func file_protoc_storage_proto_init() {
	if File_protoc_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreRequestMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protoc_storage_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*StoreV1Request_Meta)(nil),
		(*StoreV1Request_Content)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_storage_proto_goTypes,
		DependencyIndexes: file_protoc_storage_proto_depIdxs,
		MessageInfos:      file_protoc_storage_proto_msgTypes,
	}.Build()
	File_protoc_storage_proto = out.File
	file_protoc_storage_proto_rawDesc = nil
	file_protoc_storage_proto_goTypes = nil
	file_protoc_storage_proto_depIdxs = nil
}
